<?php
/* 
 * Le footer du site Placé en includes
 */
?>
<!-- ______________________ FOOTER _______________________ -->
<footer id="footer" class="clearfix site-footer" role="contentinfo">
  <div class="container">
    <div id="footer-content" class="row-fluid footer-content"> <?php print render($page['footer']); ?> </div>
    <div id="bloc_stats">
    !!!!  STATS DESACTIVEES !!!!
<?php
 // $theme_path = drupal_get_path('theme', 'cyranod7_cg');
  //include ($theme_path.'/js/code_stats.php');
  ?>
</div>    
  </div><!-- /container -->
     
</footer> <!-- /footer -->